### ISSUE TITLE
Feature request : Add Unit test cases with jest

### ISSUE THREAD

**Issue by Tushar98644** [Tushar98644/ProjectHub#305]
**Describe the solution you'd like**

We would like to request the addition of unit test cases using Jest. With Jest already configured, here are the likely tasks that the unit tests would perform: 

* Test for Functionality
* Verify Edge Cases
* Check Error Handling
* Assess Data Validation
* Evaluate Code Paths

**Comment by dhaneshragu** [comment]
For how many components do you expect to do this?

**Comment by Tushar98644** [comment]
> For how many components do you expect to do this?

Currently there are about 8 components , so i would expect a minimum of 3 to be covered up in this task

**Comment by dhaneshragu** [comment]
Hey, @Tushar98644 , Then please can you assign it to me. Also, can u tell me where the `Card` component is present as given in the existing jest test suite?

**Comment by Tushar98644** [comment]
> Hey, @Tushar98644 , Then please can you assign it to me. Also, can u tell me where the `Card` component is present as given in the existing jest test suite?

Assigned , all the components are present under `src/components` directory . The existing test case is not functional , so you can pretty much ignore that
