### ISSUE TITLE
[BUG] : Make the Admin page responsive 

### ISSUE THREAD

**Issue by Tushar98644** [Tushar98644/ProjectHub#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the ui for this page breaks for mobile devices 

### Expected Behavior

Fix the ui so that it works appropriately for all devices 

### Version

1.0.3 (Edge)

### Environment

```markdown
- OS: 
- Node:
- npm:
```

**Comment by Ir786921** [comment]
hey ,can you please assign this task to me

**Comment by Tushar98644** [comment]
> hey ,can you please assign this task to me

Assigned 👍,  try to complete it within two days time span

**Comment by Dhruv127** [comment]
Assign me

**Comment by Tushar98644** [comment]
@Ir786921 what's your update? Are you working on this or shall i reassign this to @Dhruv127

**Comment by Ir786921** [comment]
ok , Assign him

**Comment by Tushar98644** [comment]
@Dhruv127 try to complete this by Friday eod

**Comment by utsavvvv** [comment]
I want to work on this task. Please assign it to me sir @Tushar98644

**Comment by MjStar24** [comment]
I would like to work in this if not completed

**Comment by Dhruv127** [comment]
PR #322 .

**Comment by Dhruv127** [comment]
do check now PR #322

**Comment by shaurya-jain23** [comment]
I would like to work, if it is not completed
