### ISSUE TITLE
[BUG] <title> Action Button dropdown on admin page is not working

### ISSUE THREAD

**Issue by Dhruv127** [Tushar98644/ProjectHub#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

None

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by Dhruv127** [comment]
can you assign it to me , under Hacktoctober fest ?

**Comment by Tushar98644** [comment]
> can you assign it to me , under Hacktoctober fest ?

Not necessary as I would be removing it in the near future
