### ISSUE TITLE
Add Favicon in frontend of the project

### ISSUE THREAD

**Issue by HimanshuTembhe** [Tushar98644/ProjectHub#347]

**Comment by HimanshuTembhe** [comment]
@Tushar98644 pls assign this issue to me

**Comment by Tushar98644** [comment]
> @Tushar98644 pls assign this issue to me

you can drop the favicon suggestions here so that we can choose the best one

**Comment by HimanshuTembhe** [comment]
![favicon_3](https://github.com/Tushar98644/ProjectHub/assets/99601153/425a2347-e6ee-436d-a433-3770b60eba59)
![favicon_1](https://github.com/Tushar98644/ProjectHub/assets/99601153/f261bdb4-1fa7-47fc-9f60-c6cce061ccac)
![favicon_2](https://github.com/Tushar98644/ProjectHub/assets/99601153/67f1aed4-b621-4c5e-919f-4efeab8eb979)
![favicon_4](https://github.com/Tushar98644/ProjectHub/assets/99601153/95c3b8ba-d866-45d9-be2b-4a7bdccdb5ac)

**Comment by Tushar98644** [comment]
> ![favicon_3](https://user-images.githubusercontent.com/99601153/274032355-425a2347-e6ee-436d-a433-3770b60eba59.png) ![favicon_1](https://user-images.githubusercontent.com/99601153/274032561-f261bdb4-1fa7-47fc-9f60-c6cce061ccac.png) ![favicon_2](https://user-images.githubusercontent.com/99601153/274032588-67f1aed4-b621-4c5e-919f-4efeab8eb979.png) ![favicon_4](https://user-images.githubusercontent.com/99601153/274033000-95c3b8ba-d866-45d9-be2b-4a7bdccdb5ac.png)

I dont quite like them , maybe add something like the logo ?

**Comment by HimanshuTembhe** [comment]
Okay

**Comment by HimanshuTembhe** [comment]
![icons8-project-management-32](https://github.com/Tushar98644/ProjectHub/assets/99601153/1fa00649-5032-479a-92d0-56dc2cb12fb1)
![icons8-project-management-32 (1)](https://github.com/Tushar98644/ProjectHub/assets/99601153/00b0ca8d-ca2d-4cb0-bcdd-bafdf706ef12)
![icons8-project-management-96](https://github.com/Tushar98644/ProjectHub/assets/99601153/c49a43d5-e383-4913-8c57-04018b48c4a9)
![icons8-project-management-96 (1)](https://github.com/Tushar98644/ProjectHub/assets/99601153/8951e776-a399-40d3-8810-5c3f0277917d)

**Comment by Tushar98644** [comment]
the last one would be good 

> ![icons8-project-management-32](https://user-images.githubusercontent.com/99601153/274038083-1fa00649-5032-479a-92d0-56dc2cb12fb1.png) ![icons8-project-management-32 (1)](https://user-images.githubusercontent.com/99601153/274038153-00b0ca8d-ca2d-4cb0-bcdd-bafdf706ef12.png) ![icons8-project-management-96](https://user-images.githubusercontent.com/99601153/274038253-c49a43d5-e383-4913-8c57-04018b48c4a9.png) ![icons8-project-management-96 (1)](https://user-images.githubusercontent.com/99601153/274038348-8951e776-a399-40d3-8810-5c3f0277917d.png)

**Comment by HimanshuTembhe** [comment]
okay

**Comment by shaurya-jain23** [comment]
Could you assign it to me if it is not completed
