### ISSUE TITLE
[BUG] : Protect Admin route 

### ISSUE THREAD

**Issue by Tushar98644** [Tushar98644/ProjectHub#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The admin route is accessible to users who do not have admin access 

### Expected Behavior

The admin route should be available to only  users with admin privileges , correct this behaviour 

### Version

1.0.3 (Edge)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by HimanshuTembhe** [comment]
Pls assign this issue to me

**Comment by Tushar98644** [comment]
> Pls assign this issue to me

any updates @HimanshuTembhe ?
